### ISSUE TITLE
Filter by Context

### ISSUE THREAD

**Issue by adamwintle** [Sterc/Batcher#4] opened 2014-05-14 06:09 UTC
Feature request to bulk update an entire section using the same template but not across all context.

We have a scenario where we're using Babel for internationalisation with four context, English, Spanish, German and Chinese, across all the contexts there are hundreds of articles but we need to only update the template for the English language section, and leave the other three contexts with the old template. 

Being able to filter by context would be useful for a situation like this.

**Comment by joeke** [comment] 2015-12-17 20:00
Hi Adam, another helpful contribution. We'll implement it in upcoming release.

**Comment by joeke** [comment] 2017-01-25 09:14
duplicate of #11

**Closed as completed by joeke** 2017-01-25 09:14 UTC
Labels: duplicate, enhancement
